# Generated by Django 3.2.25 on 2025-04-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_game_master', to='game.gamesession'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_game_session', to='game.playerprofile'),
        ),
    ]
