# Generated by Django 3.2.25 on 2025-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20250411_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='max_players',
            field=models.IntegerField(default=8),
        ),
    ]
