# Generated by Django 3.2.25 on 2025-04-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamesession_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='max_players',
            field=models.IntegerField(default=10),
        ),
    ]
