# Generated by Django 3.2.25 on 2025-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamesession_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='step',
            field=models.IntegerField(choices=[(1, 'Step 1 - Initial Clues'), (2, 'Step 2 - More Clues'), (3, 'Step 3 - Final Clues'), (4, 'Epilogue - Resolution')], default=1, help_text='The game step when this clue becomes available'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='step',
            field=models.IntegerField(choices=[(1, 'Step 1 - Initial Clues'), (2, 'Step 2 - More Clues'), (3, 'Step 3 - Final Clues'), (4, 'Epilogue - Resolution')], default=1),
        ),
    ]
