# Generated by Django 3.2.25 on 2025-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20250411_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='scenario',
            field=models.CharField(choices=[('enchanted_forest', 'The Enchanted Forest')], default='enchanted_forest', max_length=50),
        ),
    ]
